# Generated by Django 4.2.3 on 2024-07-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('Milk', 'Milk'), ('Curd', 'Curd'), ('Ghee', 'Ghee'), ('Paneer', 'Paneer'), ('Chesse', 'Chesse'), ('Ice-Cream', 'Ice-Cream'), ('Milkshake', 'Milkshake'), ('Lassi', 'Lassi')], max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
