# Generated by Django 4.2.3 on 2024-07-26 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('milk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Karnataka', 'Karnataka'), ('Tamilnadu', 'Tamilnadu'), ('Telangana', 'Telangana'), ('Maharashtra', 'Maharashtra'), ('West Bengal', 'West Bengal'), ('Rajasthan', 'Rajasthan'), ('Gujarat', 'Gujarat'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Punjab', 'Punjab'), ('Jharkhand', 'Jharkhand'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Haryana', 'Haryana'), ('Delhi', 'Delhi'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Sikkim', 'Sikkim'), ('Kerala', 'Kerala'), ('Uttarakhand', 'Uttarakhand'), ('Other', 'Other')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
